#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### AUTODOC
#
# Prepare kubectl.
#
# This role installs Kubernetes command line tool and configures it
# on the host to make it possible to connect to the server.
#
###
---

- name: Create k8s tap-admin user
  user:
    name: tap-admin
    shell: /bin/bash
    home: /home/tap-admin
    system: yes

- name: Create k8s directories
  file:
    group: tap-admin
    mode: 0750
    owner: tap-admin
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/tap-admin/.kube"
    - "/home/tap-admin/.ssh"

- name: Download kubectl binaries
  get_url:
    url: "{{ repo_host }}/files/kubectl"
    dest: /usr/local/bin/kubectl
    mode: 0755
  register: kubectl_down

- name: Generate kubernetes bash completions
  shell: /usr/local/bin/kubectl completion bash > /etc/bash_completion.d/kubectl
  when: kubectl_down.changed

- name: Write k8s kubectl config file
  template:
    dest: /home/tap-admin/.kube/config
    group: tap-admin
    mode: 0640
    owner: tap-admin
    src: kube.config.j2

- name: Copy authorized keys for tap-admin
  copy:
    src: "{{ lookup('env','HOME') }}/.ssh/authorized_keys"
    dest: /home/tap-admin/.ssh/authorized_keys

- name: Change permissions to file with keys
  file:
    path: /home/tap-admin/.ssh/authorized_keys
    owner: tap-admin
    mode: 0640
