#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Deploy hbase rs
  cdh: 
    action: deploy_service_worker_nodes 
    service: hbase 
    host: "{{ item }}"
    password: "{{ cdh_admin_password }}"
  with_items: "{{groups['cdh-worker']}}"

- name: Set hbase service properties
  cdh: 
    action: set_config 
    password: "{{ cdh_admin_password }}"
    entity: service 
    service: hbase
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'hdfs_service', value: 'HDFS' }
    - { name: 'zookeeper_service', value: 'ZOOKEEPER' }

- name: Set options for minimal deployment
  cdh: 
    action: set_config 
    password: "{{ cdh_admin_password }}"
    entity: role
    service: hbase
    role: "{{ item.role }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { role: 'GATEWAY', name: 'hbase_client_java_heapsize', value: '52428800' }
    - { role: 'HBASERESTSERVER', name: 'hbase_restserver_java_heapsize', value: '52428800' }
    - { role: 'HBASETHRIFTSERVER', name: 'hbase_thriftserver_java_heapsize', value: '52428800' }
    - { role: 'MASTER', name: 'hbase_master_java_heapsize', value: '52428800' }
    - { role: 'REGIONSERVER', name: 'hbase_regionserver_java_heapsize', value: '52428800' }
  when: deployment_type == 'minimal'

# Here we execute command on hbase which is automatically executed in CM - CreateHbaseHome
- name: Deploy hbase master components
  cdh: 
    action: deploy_base_roles
    password: "{{ cdh_admin_password }}"
    service: hbase
    host: "{{ groups['cdh-manager'][0] }}"

- name: Start hbase service
  cdh: 
    action: service
    password: "{{ cdh_admin_password }}"
    service: hbase
    state: started
