#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Deploy hive service
  cdh: 
    action: deploy_service 
    password: "{{ cdh_admin_password }}"
    name: hive

- name: Set hive service properties
  cdh: 
    action: set_config
    password: "{{ cdh_admin_password }}"
    entity: service 
    service: hive
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'mapreduce_yarn_service', value: 'YARN' }
    - { name: 'zookeeper_service', value: 'ZOOKEEPER' }
    - { name: 'spark_on_yarn_service', value: 'SPARK_ON_YARN' }
    - { name: 'hive_metastore_database_host', value: "{{ database.host }}" }
    - { name: 'hive_metastore_database_password', value: "{{ hostvars[groups['k8s-master'][0]].passwords.databases.metastore }}" }
    - { name: 'hive_metastore_database_name', value: '{{ database.databases.metastore.name }}' }
    - { name: 'hive_metastore_database_user', value: '{{ database.databases.metastore.name }}' }
    - { name: 'hive_metastore_database_port', value: '{{ database.port }}' }
    - { name: 'hive_metastore_database_type', value: 'mysql' }

- name: Set options for minimal deployment
  cdh: 
    action: set_config 
    password: "{{ cdh_admin_password }}"
    entity: role
    service: hive
    role: "{{ item.role }}" 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { role: 'GATEWAY', name: 'hive_client_java_heapsize', value: '52428800' }
    - { role: 'HIVEMETASTORE', name: 'hive_metastore_java_heapsize', value: '52428800' }
    - { role: 'HIVESERVER2', name: 'hiveserver2_java_heapsize', value: '52428800' }
    - { role: 'WEBHCAT', name: 'hive_webhcat_java_heapsize', value: '52428800' }
  when: deployment_type == 'minimal'

- name: Deploy hive master components
  cdh: 
    action: deploy_base_roles
    password: "{{ cdh_admin_password }}"
    service: hive 
    host: "{{ groups['cdh-manager'][0] }}"

- name: Deploy hive gateways
  cdh: 
    action: deploy_service_worker_nodes
    password: "{{ cdh_admin_password }}"
    service: hive
    host: "{{ item }}"
  with_items: "{{groups['cdh-worker']}}"

- name: Start hive service
  cdh: 
    action: service
    password: "{{ cdh_admin_password }}"
    service: hive 
    state: started
