#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Deploy hue master components
  cdh: 
    action: deploy_base_roles
    password: "{{ cdh_admin_password }}" 
    service: hue 
    host: "{{ groups['cdh-manager'][0] }}"

- name: Set hue server role properties
  cdh: 
    action: set_config 
    password: "{{ cdh_admin_password }}"
    entity: service 
    service: hue 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'hue_webhdfs', value: 'HDFS-HTTPFS-1' }
    - { name: 'hue_hbase_thrift', value: 'HBASE-HBASETHRIFTSERVER' }
    - { name: 'hive_service', value: 'HIVE' }
    - { name: 'hbase_service', value: 'HBASE' }
    - { name: 'oozie_service', value: 'OOZIE' }
    - { name: 'database_host', value: "{{ database.host }}" }
    - { name: 'database_port', value: "{{ database.port }}" }
    - { name: 'database_password', value: "{{ hostvars[groups['k8s-master'][0]].passwords.databases.hue }}" }
    - { name: 'database_name', value: "{{ database.databases.hue.name }}" }
    - { name: 'database_type', value: 'mysql' }
    - { name: 'database_user', value: "{{ database.databases.hue.name }}" }

- name: Start hue service
  cdh: 
    action: service
    password: "{{ cdh_admin_password }}"
    service: hue 
    state: started

- wait_for: 
    host: "{{ groups['cdh-manager'][0] }}"
    port: 8888

