#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Deploy oozie service
  cdh: 
    action: deploy_service 
    password: "{{ cdh_admin_password }}"
    name: oozie

- name: Set oozie service properties
  cdh: 
    action: set_config
    password: "{{ cdh_admin_password }}"
    entity: service
    service: oozie
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'mapreduce_yarn_service', value: 'YARN' }

- name: Set oozie server role properties
  cdh: 
    action: set_config
    password: "{{ cdh_admin_password }}"
    entity: role
    service: oozie
    role: OOZIE_SERVER
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'oozie_database_host', value: "{{ database.host }}:{{ database.port }}" }
    - { name: 'oozie_database_password', value: "{{ hostvars[groups['k8s-master'][0]].passwords.databases.oozie }}" }
    - { name: 'oozie_database_name', value: "{{ database.databases.oozie.name }}" }
    - { name: 'oozie_database_type', value: 'mysql' }
    - { name: 'oozie_database_user', value: "{{ database.databases.oozie.name }}" }

- name: Set options for minimal deployment
  cdh: 
    action: set_config
    password: "{{ cdh_admin_password }}"
    entity: role
    service: oozie
    role: "{{ item.role }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { role: 'OOZIE_SERVER', name: 'oozie_java_heapsize', value: '52428800' }
  when: deployment_type == 'minimal'

- name: Deploy oozie master components
  cdh: 
    action: deploy_base_roles
    password: "{{ cdh_admin_password }}"
    service: oozie
    host: "{{ groups['cdh-manager'][0] }}"

- name: Start oozie service
  cdh: 
    action: service
    password: "{{ cdh_admin_password }}"
    service: oozie
    state: started


