#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Deploy yarn nm
  cdh: 
    action: deploy_service_worker_nodes 
    password: "{{ cdh_admin_password }}"
    service: yarn 
    host: "{{ item }}"
  with_items: "{{ groups['cdh-worker'] }}"

- name: Set yarn service properties
  cdh: 
    action: set_config 
    password: "{{ cdh_admin_password }}"
    entity: service 
    service: yarn 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'hdfs_service', value: 'HDFS' }

- name: Set yarn default role properties
  cdh:
    action: set_config
    password: "{{ cdh_admin_password }}"
    entity: role
    service: yarn
    role: NODEMANAGER
    name: yarn_nodemanager_local_dirs
    value: "{{ yarn.dirs.local.nodemanager }}"

- name: Set yarn role properties for hosts with disk
  cdh:
    action: set_config
    password: "{{ cdh_admin_password }}"
    entity: host
    service: yarn
    role: NODEMANAGER
    name: yarn_nodemanager_local_dirs
    value: "{{ cdh_hosts_disks[item].storage | add_suffix('/nm') | join(',') }}"
    host: "{{ item }}"
  when: cdh_hosts_disks[item].storage | length > 0
  with_items: "{{ groups['cdh-worker'] }}"

- name: Set yarn gateway role properties
  cdh: 
    action: set_config 
    password: "{{ cdh_admin_password }}"
    entity: role
    service: yarn
    role: GATEWAY
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  with_items:
    - { name: 'mapred_submit_replication', value: "{{ 3 if (worker_size | int) > 3 else worker_size }}" }

- name: Set options for minimal deployment
  cdh: 
    action: set_config 
    password: "{{ cdh_admin_password }}"
    entity: role 
    service: yarn
    role: '{{ item.role }}'
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  with_items:
    - { role: 'GATEWAY', name: 'mapreduce_client_java_heapsize', value: '52428800' }
    - { role: 'JOBHISTORY', name: 'mr2_jobhistory_java_heapsize', value: '52428800' }
    - { role: 'NODEMANAGER', name: 'node_manager_java_heapsize', value: '52428800' }
    - { role: 'RESOURCEMANAGER', name: 'resource_manager_java_heapsize', value: '52428800' }
  when: deployment_type == 'minimal'

- name: Deploy yarn history server
  cdh: 
    action: deploy_base_roles 
    password: "{{ cdh_admin_password }}"
    service: yarn-history 
    host: "{{ groups['cdh-manager'][0] }}"
 
- name: Deploy yarn master components
  cdh: 
    action: deploy_base_roles 
    password: "{{ cdh_admin_password }}"
    service: yarn
    host: "{{ groups['cdh-master-primary'][0] }}"

- name: Enable ha on yarn
  cdh: 
    action: deploy_rm_ha 
    password: "{{ cdh_admin_password }}"
    sn_host: "{{ groups['cdh-master-secondary'][0] }}"
  when: yarn.ha_enabled

- name: Start yarn service
  cdh: 
    action: service 
    password: "{{ cdh_admin_password }}"
    service: yarn
    state: started

