#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- include_vars: "{{ item }}"
  with_items:
    - config.yml
    - cluster-config.yml
    - ami.yml
    - definitions.yml

- name: Check configuration
  set_fact:
    parsed_instances: "{{ instances | parse_instances }}"

- name: Set aws requirements
  set_fact:
    requirements: {}

- name: Validate configuration
  set_fact:
    validation: "{{ instances | check_instances(requirements) }}"

- include: keys.yml

- include: vpc.yml

- include: subnet.yml

- include: sg.yml

- include: route-base.yml

- include: instances-base.yml

- include: route-cluster.yml

- include: spawn.yml
  with_dict: "{{ instances }}"

- include: lb.yml

- include: inventory.yml

- include: jumpbox-init.yml

- include: tap-configuration.yml
