#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

repository_uri: "{{ dr_clusterip }}:5000"

ca_service:
  user: "admin"
  pass:

enable_external_ssl: 'false'
external_protocol: "{{ 'https' if enable_external_ssl == 'true' else 'http' }}"

# allowed characters: [a-zA-Z0-9_-]
env_name: tap

local_domain: "{{ env_name }}.local"
dns_isolation: False

etcd:
  k8s:
    client_port: 2379
    peer_port: 2380
    enable_ssl: True
    cert_file: "/etc/kubernetes/ssl/{{ inventory_hostname }}.crt"
    key_file: "/etc/kubernetes/ssl/{{ inventory_hostname }}.key"
    ca_file: "/etc/kubernetes/ssl/ca.crt"
  skydns:
    client_port: 2381
    peer_port: 2382
    enable_ssl: True
    cert_file: "/etc/kubernetes/ssl/{{ inventory_hostname }}.crt"
    key_file: "/etc/kubernetes/ssl/{{ inventory_hostname }}.key"
    ca_file: "/etc/kubernetes/ssl/ca.crt"

etcd_catalog_replicas: "{{ [ groups['k8s-worker'] | length, 3 ] | min }}"

# Elastic Search node count. ELK creates a cluster, >=3 nodes are recommended.
elastic_nodes: 1

flannel_backend: "vxlan"
flannel_host_prefix: 24
flannel_ip_range: 10.20.0.0/16

uaa_insecure_port: 8080

k8s_api_insecure_port: 8080
k8s_api_secure_port: 8443
k8s_service_ip_range: 10.10.0.0/16
kubedns_clusterip: "{{ k8s_service_ip_range | ipaddr('10') | ipaddr('address') }}"
dr_clusterip: "{{ k8s_service_ip_range | ipaddr('15') | ipaddr('address') }}"
logstash_clusterip: "{{ k8s_service_ip_range | ipaddr('16') | ipaddr('address') }}"
ca_service_clusterip: "{{ k8s_service_ip_range | ipaddr('17') | ipaddr('address') }}"

uaa_postgres_pass:
ws_postgres_pass:
zk_user_pass:
psnapshot_postgres_pass:

# possible values: aws, bare-metal
provider: "bare-metal"

cli_version: 0.8.0
k8s_version: 1.3.0

upgrade_kernel: False
kernel_version: kernel
