#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### AUTODOC
#
# Configure mysql for CDH purposes.
#
# Create DB for CDH metastore and configure user privileges.
#
###
---

- name: Create DB metastore
  mysql_db:
    name: "{{ item.value.name }}"
    state: present
    login_user: "{{ database.user }}"
    login_password: "{{ hostvars[groups['k8s-master'][0]].passwords.databases.database }}"
    login_unix_socket: /data/main/mysql/mysql.sock
  with_dict: '{{ database.databases }}'

- name: Grant privileges all users
  mysql_user:
    name: "{{ item.value.name }}"
    host: "{{ item.value.access }}"
    password: "{{ hostvars[groups['k8s-master'][0]].passwords.databases[item.key] }}"
    priv: "{{ item.value.name }}.*:ALL" 
    append_privs: no
    login_user: "{{ database.user }}"
    login_password: "{{ hostvars[groups['k8s-master'][0]].passwords.databases.database }}"
    login_unix_socket: /data/main/mysql/mysql.sock
  with_dict: "{{ database.databases }}"
  notify: Flush MySQL

- name: Grant privileges all users
  mysql_user:
    name: "{{ item.value.name }}"
    host: "%"
    password: "{{ hostvars[groups['k8s-master'][0]].passwords.databases[item.key] }}"
    priv: "{{ item.value.name }}.*:ALL"
    append_privs: no
    login_user: "{{ database.user }}"
    login_password: "{{ hostvars[groups['k8s-master'][0]].passwords.databases.database }}"
    login_unix_socket: /data/main/mysql/mysql.sock
  with_dict: '{{ database.databases }}'
  notify: Flush MySQL
