#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: CA Get CA
  uri:
    url: "http://{{ ca_service_clusterip }}/api/v1/ca"
    method: GET
    user: "{{ hostvars[groups['k8s-master'][0]].ca_service.user }}"
    password: "{{ hostvars[groups['k8s-master'][0]].passwords.ca_service.pass }}"
    force_basic_auth: yes
    status_code: 200
    return_content: yes
  register: ca_cert

- name: Create restore Job
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data: "{{ lookup('template', item + '.job.j2') }}"
  with_items: "{{ backup_job_list }}"

- name: Wait until job finishes
  uri:
    url: "http://localhost:8080/apis/extensions/v1beta1/namespaces/default/jobs/{{ item }}/status"
    method: GET
    return_content: yes
    validate_certs: no
  register: job_status
  until: job_status.json.status.succeeded is defined
  retries: 30
  delay: 10
  with_items: "{{ backup_job_list }}"
