#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Create a ConfigMap instance app-launcher-helper
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: app-launcher-helper
      data:
        host: http://app-launcher-helper.tap.gotapaas.eu
    state: present


- name: Create a ConfigMap instance das
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: das
      data:
        host: http://data-acquisition
        http-proxy: ""
        https-proxy: ""
    state: present


- name: Create a ConfigMap instance hdfs-uploader
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: hdfs-uploader
      data:
        host: http://uploader
    state: present



- name: Create a ConfigMap instance kubernetes-broker
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: kubernetes-broker
      data:
        host: http://kubernetes-broker.tap.gotapaas.eu
    state: present



- name: Create a ConfigMap instance latest-events-service
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: latest-events-service
      data:
        host: http://latest-events-service.tap.gotapaas.eu
    state: present



- name: Create a ConfigMap instance platform-context
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: platform-context
      data:
        host: http://platform-context.tap.gotapaas.eu
    state: present


- name: Create a ConfigMap instance platform-operations
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: platform-operations
      data:
        host: http://platform-operations.tap.gotapaas.eu
    state: present


- name: Create a ConfigMap instance router-metrics-provider
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: router-metrics-provider
      data:
        host: http://router-metrics-provider.tap.gotapaas.eu
    state: present





- name: Create a ConfigMap instance service-exposer
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: service-exposer
      data:
        host: http://service-exposer.tap.gotapaas.eu
    state: present


- name: CONSOLE Create a deployment instance
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: console
        labels:
          tap_app_type: CORE
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              app: console
          spec:
            imagePullSecrets:
              - name: private-tap-repo-secret
            containers:
            - name: console
              image: "{{ repository_uri }}/console:{{ tap_version }}"
              ports:
                - containerPort: "{{ k8s_api_insecure_port }}"
                  protocol: TCP
              resources:
                limits:
                  memory: "{{ console_memory_limit }}"
                requests:
                  memory: "{{ console_memory_limit }}"
              env:
                - name: DATASET_PUBLISHER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: dataset-publisher
                      key: uri
                - name: APP_LAUNCHER_HELPER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: app-launcher-helper
                      key: host
                - name: MODEL_CATALOG_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: model-catalog
                      key: host
                - name: USER_MANAGEMENT_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: user-management
                      key: host
                - name: PLATFORM_SNAPSHOT_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: platform-snapshot
                      key: host
                - name: ROUTER_METRICS_PROVIDER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: router-metrics-provider
                      key: host
                - name: DATAAQUISITIONSERVICE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: das
                      key: host
                - name: WORKFLOW_SCHEDULER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: workflow-scheduler
                      key: host
                - name: HDFS_UPLOADER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: hdfs-uploader
                      key: host
                - name: SERVICECATALOG_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: api-service
                      key: host
                - name: API_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: api-service
                      key: host
                - name: PLATFORM_DOMAIN
                  valueFrom:
                    configMapKeyRef:
                      name: platform
                      key: domain
                - name: H2O_ENGINES_PUBLISHER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: h2o-scoring-engine-publisher
                      key: hostname
                - name: TAP_SCORING_ENGINE_PUBLISHER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: scoringengine-mc-int
                      key: hostname
                - name: LATEST_EVENTS_SERVICE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: latest-events-service
                      key: host
                - name: SERVICE_EXPOSER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: service-exposer
                      key: host
                - name: METRICS_GRAFANA_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: grafana
                      key: host
                - name: METRICS_GRAFANA_TAP_DOMAIN_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: grafana
                      key: host-tap-domain
                - name: DATACATALOG_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: data-catalog
                      key: uri
                - name: PLATFORMCONTEXT_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: platform-context
                      key: host
                - name: PLATFORM_TESTS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: platform-tests
                      key: host
                - name: KUBERNETES_BROKER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: kubernetes-broker
                      key: host
                - name: SSO_API_ENDPOINT
                  valueFrom:
                     configMapKeyRef:
                      name: sso
                      key: api-endpoint
                - name: SSO_AUTHORIZATION_URI
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: authorization-uri
                - name: SSO_CHECK_TOKEN_URI
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: check-token-uri
                - name: SSO_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: client-id
                - name: SSO_CLIENT_SECRET
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: client-secret
                - name: SSO_EMAIL
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: email
                - name: SSO_LOGOUT_URI
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: logout-uri
                - name: SSO_TOKEN_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: token-key
                - name: SSO_TOKEN_URI
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: token-uri
                - name: SSO_UAA_URI
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: uaa-uri
                - name: SSO_USER_INFO_URI
                  valueFrom:
                    configMapKeyRef:
                      name: sso
                      key: user-info-uri
                - name: http_proxy
                  valueFrom:
                    configMapKeyRef:
                      name: das
                      key: http-proxy
                - name: https_proxy
                  valueFrom:
                    configMapKeyRef:
                      name: das
                      key: https-proxy
                - name: GRAFANA_BASIC_USER
                  valueFrom:
                    configMapKeyRef:
                      name: "grafana"
                      key: "grafana-basic-user"
                - name: GRAFANA_BASIC_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: "grafana"
                      key: "grafana-basic-password"
    state: present

- name: Console Create ingress
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    state: present
    inline_data:
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: console
        annotations:
          useExternalSsl: "{{ enable_external_ssl }}"
      spec:
        rules:
        - host: "console.{{ tap_domain_name }}"
          http:
            paths:
            - path: "/"
              backend:
                serviceName: "console"
                servicePort: 8080
