#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- include: data-catalog-facts.yml

- name: Create directory for k8s templates
  file: path=/home/{{ ansible_user }}/tap_templates state=directory

- include: create-resource.yml dir=/home/{{ ansible_user }}/tap_templates name={{item.name}} templ={{item.templ}}
  with_items:
  - { name: 'Data Catalog Config', templ: 'data-catalog-config.yaml.j2' }
  - { name: 'NATS',                templ: 'nats.yaml.j2' }
  - { name: 'Data Catalog Store',  templ: 'data-catalog-store-deployment.yaml.j2' }
  - { name: 'Data Catalog',        templ: 'data-catalog-deployment.yaml.j2' }
  - { name: 'Downloader Config',   templ: 'downloader-config.yaml.j2' }
  - { name: 'Downloader',          templ: 'downloader-deployment.yaml.j2' }
  - { name: 'Metadata Parser',     templ: 'metadata-parser-deployment.yaml.j2' }
  - { name: 'Request Store',       templ: 'request-store-deployment.yaml.j2' }
  - { name: 'Data Acquisition',    templ: 'data-acquisition-deployment.yaml.j2' }
  - { name: 'Uploader',            templ: 'uploader-deployment.yaml.j2' }
  - { name: 'Dataset Publisher',   templ: 'dataset-publisher-deployment.yaml.j2' }
