#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
- name: Create a docker registry instance
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
        apiVersion: extensions/v1beta1
        kind: Deployment
        metadata:
          name: docker-registry
        spec:
          replicas: 1
          template:
            metadata:
              labels:
                app: docker-registry
            spec:
              containers:
              - name: docker-registry
                image: "registry:2"
                imagePullPolicy: IfNotPresent
                resources:
                  limits:
                    memory: "{{ docker_registry_memory_limit }}"
                  requests:
                    memory: "{{ docker_registry_memory_limit }}"
                ports:
                  - containerPort: 5000
                    protocol: TCP
                volumeMounts:
                  - mountPath: /var/lib/registry/
                    name: registry-data-volume
                    readOnly: false
              volumes:
              - name: registry-data-volume
                hostPath:
                 path: /var/lib/tmp-tap-images-registry-data-dir/data
    state: present

#TODO please remove ignore errors

- name: Create a service for a docker registry
  ignore_errors: yes
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
        apiVersion: v1
        kind: Service
        metadata:
          labels:
            name: docker-registry-service
          name: docker-registry-service
        spec:
          ports:
            - port: 5000
              nodePort: "{{ docker_registry_nodeport }}"
          selector:
            app: docker-registry
          type: NodePort
    state: present

# at the moment below fact is not needed
#- set_fact: repository_uri="{{ svc_details.api_response[0]["spec"]["clusterIP"] }}:{{ docker_registry_nodeport }}"

- set_fact: repository_uri="127.0.0.1:{{ docker_registry_nodeport }}"


