#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: TEMPLATE-REPOSITORY Get CertKey
  uri:
    url: "http://{{ ca_service_clusterip }}/api/v1/certkey/template-repository"
    method: GET
    user: "{{ ca_service.user }}"
    password: "{{ hostvars[groups['k8s-master'][0]].passwords.ca_service.pass }}"
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    timeout: 60
  register: certkey

- name: TEMPLATE-REPOSITORY create cert and key secret for nginx
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: "Secret"
      metadata:
        name: "template-repository-certkey"
      data:
        ssl.crt: "{{ certkey.json['cert'] | b64encode }}"
        ssl.key: "{{ certkey.json['key'] | b64encode }}"

- name: TEMPLATE-REPOSITORY Create a ConfigMap instance
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: "ConfigMap"
      apiVersion: "v1"
      metadata:
        name: "template-repository"
        labels:
          app: "template-repository"
      data:
        host: "template-repository"
        port: "80"
        ssl-port: "443"
        use-external-ssl-flag: "{{ enable_external_ssl }}"
        user: "admin"
        pass: "password"
        domain: "{{ tap_domain_name }}"
        generic-application-template-id: "52b31177-fef1-49af-7aa4-90382f7be43e"
        generic-service-template-id: "0e7d1029-216c-454d-8caa-33a91c5b02df"
        broker-log-level: "INFO"

- name: TEMPLATE-REPOSITORY  Create a service
  ignore_errors: yes
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data:
      kind: "Service"
      apiVersion: "v1"
      metadata:
        name: "template-repository"
        labels:
          app: "template-repository"
      spec:
        type: "ClusterIP"
        selector:
          app: "template-repository"
        ports:
          - port: 80
            protocol: "TCP"
            name: "rest"
          - port: 443
            protocol: "TCP"
            name: "rest-ssl"
    state: present


- name: TEMPLATE-REPOSITORY Create a deployment
  tapkube:
    api_endpoint: "127.0.0.1:{{ k8s_api_insecure_port }}"
    insecure: true
    inline_data: "{{ lookup('template', 'apps/template-repository.deployment.j2') }}"
    state: present
