#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Create boot docker registry data directory
  file:
    path: /var/lib/docker-registry/boot
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: root
    recurse: yes

- name: Copy boot registry data
  become: no
  synchronize:
    src: tap-base-images/
    dest: /var/lib/docker-registry/boot/

- name: Secure boot docker registry data directory
  file:
    path: /var/lib/docker-registry/boot
    state: directory
    owner: root
    group: root
    recurse: yes

- name: Install docker registry
  yum:
    name: docker-distribution
    update_cache: true
    state: latest

- name: Fill config template
  template:
    src: docker-registry.config.j2
    dest: /etc/docker-distribution/registry/config.yml
    mode: 0755
  notify:
    - Restart docker registry

- name: Start docker registry
  service:
    name: docker-distribution
    state: started
    enabled: yes

- name: Wait for docker registry port
  wait_for:
    port: 5000
    timeout: 20
    delay: 1
