#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Install required OS packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ zabbix_server.os_packages }}"

- name: Install required Python libs
  pip:
    name: "{{ repo_host }}/pip/{{ item }}"
  with_items: "{{ zabbix_server.python_packages }}"

- name: Start redis service
  service:
    name: redis
    state: started
    enabled: yes
  
- name: Create zabbix directories
  file:
    dest: "{{ item }}"
    owner: zabbix
    group: zabbix
    state: directory
    recurse: yes
  with_items:
    - /var/lib/zabbix
    - "{{ zabbix_server.server_conf.ExternalScripts }}"
    - "{{ zabbix_server.server_conf.AlertScriptsPath }}/statuspage"
  
- name: Create zabbix server configuration file
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix
    group: zabbix
    mode: 0600
  notify: Restart zabbix server

- name: Create CDH healthcheck script
  copy:
    src: clouderator.py
    dest: "{{ zabbix_server.server_conf.ExternalScripts }}"
    owner: zabbix
    group: zabbix
    mode: 0777

- name: Create statuspage alertscript
  template:
    src: statuspage_alert.j2
    dest: "{{ zabbix_server.server_conf.AlertScriptsPath }}/environment_status"
    owner: zabbix
    group: zabbix
    mode: 0600

- name: Create statuspage alertscript log file
  file:
    path: "{{ zabbix_server.server_conf.AlertScriptsPath }}/statuspage/statuspage.log"
    state: touch
    owner: zabbix
    group: zabbix
    mode: 0600

- name: Start zabbix server
  service:
    name: zabbix-server
    state: started
    enabled: yes
