#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---


- name: Install the NTP daemon
  yum:
    name: ntp
    state: installed

- name: Configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Check if any ntp server is defined
  fail:
    msg: "You have to define at least one ntp server"
  when: ntp_servers | length == 0

- name: Get ntp status
  shell: ntpstat
  register: ntp_stat
  changed_when: ntp_stat.rc != 0
  failed_when: false

- name: Stop the NTP daemon service
  service:
    name: ntpd
    state: stopped
    enabled: yes
  when: ntp_stat|changed

- name: "Force NTP update for {{ ntp_servers | join(',') }}"
  shell: "ntpdate {{ ntp_servers | join(' ') }}"
  when: ntp_stat|changed

# pause does not work with when parameter
- name: Wait for NTP to refresh - waiting for port 22 with delay 10s - act like sleep
  wait_for:
    port: 22
    delay: 10
  when: ntp_stat|changed

- name: Restart the NTP daemon service 
  service:
    name: ntpd
    state: restarted
    enabled: yes
  when: ntp_stat|changed

# pause does not work with when parameter
- name: Wait for NTP to refresh - waiting for port 22 with delay 20s - act like sleep
  wait_for:
    port: 22
    delay: 20
  when: ntp_stat|changed

