#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### AUTODOC
#
# Configure nginx to be a HTTP router.
#
# It is necessary to let in network traffic from outside the platform
# and to serve internal repository.
#
###
---

- name: Install nginx
  yum: name=nginx state=installed

- name: Write nginx config file
  template: dest=/etc/nginx/nginx.conf src=nginx.conf.j2
  notify:
    - Restart nginx

- name: Remove default configuration
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Enable and start nginx
  service: name=nginx enabled=yes state=started
